[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7.0"
dotenvy = "0.15"
serde = "1"
serde_json = "1"

entity = { path = "../entity" }
service = {path = "../service"}
